// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "l21OnDN8o9m7WMSllWnDKyI8Xjfv5KpLQblLCLOalAv7cL5h4HhWgRkJAr1z7oq2hAV2mo";
}
}
}

